[package]
name = "miaq"
version = "0.1.0"
edition = "2024"
authors = ["hx4c"]
description = "Make It a Quote bot, but free"

[lib]
crate-type = ["cdylib"]

[dependencies]
ab_glyph = "0.2"
ed25519-dalek = "3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
gif = "0.14"
hex = "0.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
serde_json = "1"
twilight-model = "0.17"
twilight-util = { version = "0.17", features = ["builder"] }
worker = "0.8"

[profile.release]
lto = true
codegen-units = 1
