[package]
name = "miaq"
version = "0.1.0"
edition = "2024"
authors = ["hx4c"]
description = "Make It a Quote bot, but free"

[lib]
crate-type = ["cdylib"]

[dependencies]
ed25519-dalek = "3"
hex = "0.4"
serde_json = "1"
twilight-model = "0.17"
twilight-util = { version = "0.17", features = ["builder"] }
worker = "0.8"

[profile.release]
lto = true
codegen-units = 1
